version: '3.6'
# Requires Docker v18.02 or higher.

#####################################################################
#   The DockerPHP Project                                           #
#   https://github.com/phpexpertsinc/docker-php                     #
#   License: MIT                                                    #
#                                                                   #
#   Copyright © 2018-2020 PHP Experts, Inc. <sales@phpexperts.pro>  #
#       Author: Theodore R. Smith <theodore@phpexperts.pro>         #
#      PGP Sig: 4BF826131C3487ACD28F2AD8EB24A91DD6125690            #
#####################################################################

services:
  web:
    image: phpexperts/web:nginx-php7.4-debug
    volumes:
      - .:/var/www:delegated
      - ./docker/web:/etc/nginx/custom


###### CUSTOM EDITS START HERE ######
  postgres:
    image: postgres:12.3
    volumes:
      - /var/lib/docker/postgres/${DB_DATABASE}:/var/lib/postgresql

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
# Uncomment if you want it to be exposed system-wide.
#    db:
#      ports:
#        - 5432:5432

  redis:
    image: redis:3.2
    entrypoint:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
      - --loglevel notice


